CREATE TABLE users (
    id BIGSERIAL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100),
    username VARCHAR(100),
    avatar_url VARCHAR(255) NOT NULL,
    day_streak INT NOT NULL DEFAULT 0,
    daily_goal INT NOT NULL DEFAULT 5 CHECK ( daily_goal BETWEEN 5 AND 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);